name: 📚 퀴즈 풀이 인증
description: 퀴즈 문제에 대한 풀이 인증용 이슈 템플릿입니다.
labels: [quiz, 풀이인증]
body:
  - type: input
    id: problem-link
    attributes:
      label: 문제 링크
      description: 문제 링크를 입력하세요.
      placeholder: 예) https://www.acmicpc.net/problem/1234
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 문제
      description: 문제 내용
      placeholder: 예) Promise then은 microtask queue에서 실행되므로…
    validations:
      required: true
